export const projectsArr = [
  {
    tittle: "Old portfolio",
    key: 1,
    description: "my first portfolio",
    img: {},
    technology: ["javascript", "html", "sass"],
    buttonGitHub: "",
    buttonPage: "",
  },
  {
    tittle: "Old portfolio1",
    key: 2,
    description: "my first portfolio",
    img: {},
    technology: ["javascript", "html", "sass"],
    buttonGitHub: "",
    buttonPage: "",
  },
  {
    tittle: "Old portfolio3",
    key: 3,
    description: "my first portfolio",
    img: {},
    technology: ["javascript", "html", "sass"],
    buttonGitHub: "",
    buttonPage: "",
  },
  {
    tittle: "Old portfolio",
    key: 4,
    description: "my first portfolio",
    img: {},
    technology: ["javascript", "html", "sass"],
    buttonGitHub: "",
    buttonPage: "",
  },
  {
    tittle: "Old portfolio",
    key: 5,
    description: "my first portfolio",
    img: {},
    technology: ["javascript", "html", "sass"],
    buttonGitHub: "",
    buttonPage: "",
  },
  {
    tittle: "Old portfolio",
    key: 5,
    description: "my first portfolio",
    img: {},
    technology: ["javascript", "html", "sass"],
    buttonGitHub: "",
    buttonPage: "",
  },
  {
    tittle: "Old portfolio",
    key: 5,
    description: "my first portfolio",
    img: {},
    technology: ["javascript", "html", "sass"],
    buttonGitHub: "",
    buttonPage: "",
  },
  {
    tittle: "Old portfolio",
    key: 5,
    description: "my first portfolio",
    img: {},
    technology: ["javascript", "html", "sass"],
    buttonGitHub: "",
    buttonPage: "",
  },
  {
    tittle: "Old portfolio",
    key: 5,
    description: "my first portfolio",
    img: {},
    technology: ["javascript", "html", "sass"],
    buttonGitHub: "",
    buttonPage: "",
  },
  {
    tittle: "Old portfolio",
    key: 5,
    description: "my first portfolio",
    img: {},
    technology: ["javascript", "html", "sass"],
    buttonGitHub: "",
    buttonPage: "",
  },
];
